# Generated by Django 2.2.6 on 2019-10-25 00:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0011_auto_20191024_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_type', models.CharField(choices=[('FP', 'First Payout'), ('LP', 'Last Payout')], max_length=2)),
                ('status', models.CharField(choices=[('PN', 'Pending'), ('PD', 'Paid')], default='PN', max_length=2)),
                ('amount', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=12)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1990), django.core.validators.MaxValueValidator(2050)])),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale')),
            ],
        ),
    ]
