# Generated by Django 2.2.6 on 2019-10-25 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.PositiveIntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payout',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='payout',
            name='year',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(limit_value=1990), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
