# Generated by Django 2.2.5 on 2019-10-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonus',
            options={'verbose_name': 'Bonus', 'verbose_name_plural': 'Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='cardealerbonus',
            options={'verbose_name': 'Car Dealer Bonus', 'verbose_name_plural': 'Car Dealer Bonuses'},
        ),
        migrations.AlterModelOptions(
            name='multiplier',
            options={'verbose_name': 'Multiplier', 'verbose_name_plural': 'Multipliers'},
        ),
        migrations.AlterModelOptions(
            name='paymenttermintz',
            options={'verbose_name': 'Payment Term Incentivization', 'verbose_name_plural': 'Payment Term Incentivizations'},
        ),
        migrations.AlterField(
            model_name='bonus',
            name='contract_volume_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
