# Generated by Django 2.2.5 on 2019-10-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0003_auto_20191010_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttermintz',
            old_name='max_payment_term',
            new_name='max_payment_terms',
        ),
    ]
