# Generated by Django 2.2.5 on 2019-10-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0005_auto_20191010_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='min_value',
            field=models.PositiveIntegerField(),
        ),
    ]
