# Generated by Django 2.2.5 on 2019-10-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0006_auto_20191010_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_percent', models.FloatField(verbose_name='First Payout Percent')),
                ('lp_percent', models.FloatField(verbose_name='Last Payout Percent')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calcons.Duration')),
            ],
        ),
    ]
