# Generated by Django 2.2.5 on 2019-10-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0007_payout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='duration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='calcons.Duration'),
        ),
    ]
