# Generated by Django 2.2.5 on 2019-10-10 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcons', '0008_auto_20191010_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonus',
            old_name='contract_volume_to',
            new_name='max_contract_volume',
        ),
        migrations.RenameField(
            model_name='bonus',
            old_name='contract_volume_from',
            new_name='min_contract_volume',
        ),
    ]
