# Generated by Django 2.2.6 on 2019-10-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='executive_description',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
