# Generated by Django 2.2.5 on 2019-10-10 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('sale_date', models.DateField()),
                ('setup_fee', models.PositiveIntegerField()),
                ('contract_volume', models.PositiveIntegerField()),
                ('monthly_budget', models.PositiveIntegerField()),
                ('duration_from', models.PositiveIntegerField()),
                ('duration_upto', models.PositiveIntegerField()),
                ('management_fee', models.PositiveIntegerField()),
                ('car_dealer_amount', models.PositiveIntegerField()),
                ('payment_terms', models.PositiveIntegerField()),
                ('agent_comment', models.TextField(blank=True)),
                ('first_commission_paid', models.BooleanField(default=False)),
                ('last_commission_paid', models.BooleanField(default=False)),
                ('first_commission_pay_on', models.DateField(blank=True, null=True)),
                ('last_commission_pay_on', models.DateField(blank=True, null=True)),
                ('finance_comment', models.TextField(blank=True)),
                ('commission_applicable', models.FloatField(blank=True, null=True)),
                ('payment_term_intz', models.PositiveIntegerField(blank=True, null=True)),
                ('car_dealer_bonus', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplier_applicable', models.FloatField(blank=True, null=True)),
                ('setup_fee_payout', models.PositiveIntegerField(blank=True, null=True)),
                ('first_payout', models.PositiveIntegerField(blank=True, null=True)),
                ('second_payout', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_payout', models.PositiveIntegerField(blank=True, null=True)),
                ('total_commission', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_id', models.CharField(default=sales.models.sale_id_generator, max_length=32)),
                ('status', models.CharField(choices=[('CR', 'Created'), ('AP', 'Approved'), ('CP', 'Completed'), ('DC', 'Declined')], default='CR', max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
