# Generated by Django 2.2.5 on 2019-10-10 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='duration_from',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='duration_upto',
        ),
    ]
