# Generated by Django 2.2.5 on 2019-10-10 02:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191010_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
