# Generated by Django 2.2.5 on 2019-09-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
