# Generated by Django 2.2.5 on 2019-10-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20191010_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='calcons.Duration'),
        ),
    ]
