# Generated by Django 2.2.5 on 2019-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190929_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('AP', 'Approved'), ('CP', 'Completed'), ('DC', 'Declined')], default='CR', max_length=2),
        ),
    ]
