# Generated by Django 2.2.5 on 2019-10-10 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20191010_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calcons.Duration'),
            preserve_default=False,
        ),
    ]
