# Generated by Django 2.2.5 on 2019-10-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20191010_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='second_payout',
        ),
        migrations.AddField(
            model_name='sale',
            name='last_payout',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
