# Generated by Django 2.2.5 on 2019-10-10 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20191010_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='total_commission',
            new_name='total_payout',
        ),
    ]
