# Generated by Django 2.2.5 on 2019-10-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20191010_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_name',
            new_name='campaign_name',
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent_comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
