# Generated by Django 2.2.6 on 2019-10-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20191010_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('PR', 'Process'), ('AP', 'Approved'), ('CP', 'Completed'), ('DC', 'Declined')], default='CR', max_length=2),
        ),
    ]
