# Generated by Django 2.2.6 on 2019-10-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20191024_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='first_commission_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='first_commission_pay_on',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='last_commission_paid',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='last_commission_pay_on',
        ),
    ]
