# Generated by Django 2.2.6 on 2019-10-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20191025_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PA', 'Pending'), ('AP', 'Approved'), ('CP', 'Completed'), ('DC', 'Declined')], default='PA', max_length=2),
        ),
    ]
