# Generated by Django 2.2.6 on 2019-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20191026_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='first_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='first_commission_pay_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_commission_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='last_commission_pay_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
