# Generated by Django 2.2.5 on 2019-09-29 13:24

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=products.models.product_id_generator, max_length=32),
        ),
    ]
